  CREATE TABLE clients (
id  integer,
id_ecad   character varying(255),
brand character varying(255),
name character varying(255),
address character varying(255),
street character varying(255),
house character varying(255),
ext_address character varying(255),
city_name_geographic character varying(255),
city_district character varying(255),
region_name_geographic character varying(255),
area_name_geographic character varying(255),
fias_id character varying(255),
fias_level character varying(255),
kladr_id character varying(255),
capital_marker character varying(255),
okato character varying(255),
oktmo character varying(255),
tax_office character varying(255),
timezone character varying(255),
geo_lat character varying(255),
geo_lon character varying(255),
beltway_hit character varying(255),
beltway_distance character varying(255),
qc_geo character varying(255),
salon_code character varying(255),
partner_code character varying(255),
open_date date,
representative_full_name character varying(255),
chain_name character varying(255),
com_mreg character varying(255),
com_reg character varying(255),
com_sect character varying(255),
crer character varying(255),
technolog_full_name character varying(255),
region_name character varying(255),
partner character varying(255),
partner_private_code character varying(255),
full_adress character varying(255),
row character varying(255),
response character varying(255)

 ); 